In [21]:
import tensorflow as tf
from tensorflow.keras import models
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler

samsung_df = pd.read_csv('005930.KS.csv',encoding='utf-8-sig')
samsung_df.dropna(inplace=True)
samsung_df.reset_index(inplace=True,drop=True)
print(samsung_df.head(5))
'''
samsung_df.hist()
plt.show()
plt.figure(figsize=(7,4))
plt.title('Samsung elec stock price')
plt.xlabel('price')
plt.ylabel('period')
plt.grid()
plt.plot(samsung_df['Adj Close'], label='Adj Close',color='b')
plt.legend(loc='best')
plt.show()
'''

         Date     Open     High      Low    Close     Adj Close      Volume
0  2010-01-04  16060.0  16180.0  16000.0  16180.0  13134.010742  11950800.0
1  2010-01-05  16520.0  16580.0  16300.0  16440.0  13345.065430  27925850.0
2  2010-01-06  16580.0  16820.0  16520.0  16820.0  13653.530273  22948850.0
3  2010-01-07  16820.0  16820.0  16260.0  16260.0  13198.952148  22107950.0
4  2010-01-08  16400.0  16420.0  16120.0  16420.0  13328.830078  14777550.0

"\nsamsung_df.hist()\nplt.show()\nplt.figure(figsize=(7,4))\nplt.title('Samsung elec stock price')\nplt.xlabel('price')\nplt.ylabel('period')\nplt.grid()\nplt.plot(samsung_df['Adj Close'], label='Adj Close',color='b')\nplt.legend(loc='best')\nplt.show()\n"

In [22]:
#samsung_df['Volume'] = samsung_df['Volume'].replace(0,np.nan)
print(samsung_df.isna().sum())

samsung_df['3MA'] = 0
samsung_df['5MA'] = 0


for i in range(2,len(samsung_df),1):
    
    samsung_df.loc[i,('3MA')] = samsung_df.loc[i-2:i,('Adj Close')].mean()

for i in range(4,len(samsung_df),1):
    samsung_df.loc[i,('5MA')] = samsung_df.loc[i-4:i,('Adj Close')].mean()

samsung_df

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

,Date,Open,High,Low,Close,Adj Close,Volume,3MA,5MA
0,2010-01-04,16060.0,16180.0,16000.0,16180.0,13134.010742,11950800.0,0.000000,0.000000
1,2010-01-05,16520.0,16580.0,16300.0,16440.0,13345.065430,27925850.0,0.000000,0.000000
2,2010-01-06,16580.0,16820.0,16520.0,16820.0,13653.530273,22948850.0,13377.535482,0.000000
3,2010-01-07,16820.0,16820.0,16260.0,16260.0,13198.952148,22107950.0,13399.182617,0.000000
4,2010-01-08,16400.0,16420.0,16120.0,16420.0,13328.830078,14777550.0,13393.770833,13332.077734
...,...,...,...,...,...,...,...,...,...
2831,2021-07-01,80500.0,80600.0,80000.0,80100.0,80100.000000,13382882.0,80600.000000,81060.000000
2832,2021-07-02,80000.0,80400.0,79900.0,80000.0,80000.000000,8753097.0,80266.666667,80740.000000
2833,2021-07-05,80100.0,80800.0,80000.0,80400.0,80400.000000,8330969.0,80166.666667,80440.000000
2834,2021-07-06,80600.0,81200.0,80500.0,81200.0,81200.000000,12131651.0,80533.333333,80480.000000
2835,2021-07-07,81200.0,81300.0,80300.0,80800.0,80800.000000,15992202.0,80800.000000,80500.000000

In [24]:
scaler = MinMaxScaler()
scale_cols = ['Open','High','Low','Close','Adj Close','3MA','5MA','Volume']

scaled_df= scaler.fit_transform(samsung_df[scale_cols])

scaled_df = pd.DataFrame(scaled_df, columns=scale_cols)
print(scaled_df)

          Open      High       Low     Close  Adj Close       3MA       5MA  \
0     0.031062  0.027034  0.033658  0.033333   0.024657  0.000000  0.000000
1     0.037066  0.031861  0.037602  0.036693   0.027314  0.000000  0.000000
2     0.037849  0.034757  0.040494  0.041602   0.031198  0.148584  0.000000
3     0.040981  0.034757  0.037076  0.034367   0.025474  0.148825  0.000000
4     0.035500  0.029930  0.035235  0.036434   0.027109  0.148765  0.148859
...        ...       ...       ...       ...        ...       ...       ...
2831  0.872096  0.804490  0.875099  0.859173   0.867827  0.895225  0.905071
2832  0.865570  0.802076  0.873784  0.857881   0.866568  0.891522  0.901498
2833  0.866875  0.806903  0.875099  0.863049   0.871604  0.890412  0.898149
2834  0.873401  0.811731  0.881672  0.873385   0.881677  0.894484  0.898595
2835  0.881232  0.812937  0.879043  0.868217   0.876641  0.897446  0.898819

        Volume
0     0.132336
1     0.309235
2     0.254123
3     0.244811
4     0.163638
...        ...
2831  0.148195
2832  0.096927
2833  0.092252
2834  0.134339
2835  0.177089

[2836 rows x 8 columns]

In [25]:
sam_feat_cols = ['3MA','5MA','Adj Close']
label_cols = ['Adj Close']

label_df = pd.DataFrame(scaled_df,columns=label_cols)
feature_df = pd.DataFrame(scaled_df,columns=sam_feat_cols)

label_np = label_df.to_numpy()
feature_np = feature_df.to_numpy()

In [26]:
# 입력 파라미터 featurn, label -> numpy type

def make_sequence_dataset(feature,label,window_size):
    
    feature_list = []
    label_list = []
    
    for i in range(len(feature) - window_size):
        
        feature_list.append(feature[i:i+window_size])
        label_list.append(label[i+window_size])
        
    return np.array(feature_list) , np.array(label_list)

In [27]:
window_size = 40
X,Y = make_sequence_dataset(feature_np,label_np,window_size)

print(X.shape, Y.shape)

(2796, 40, 3) (2796, 1)

In [28]:
split = -200

x_train = X[0:split]
y_train = Y[0:split]

x_test = X[split:]
y_test = Y[split:]

print(x_train.shape , y_train.shape)
print(x_test.shape , y_test.shape)

(2596, 40, 3) (2596, 1)
(200, 40, 3) (200, 1)

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM
print(x_train[0])
print(x_train[0].shape)

model = Sequential()

model.add(LSTM(128,
              activation='tanh',
              input_shape = x_train[0].shape))

model.add(Dense(1,activation='linear'))

model.summary()

[[0.         0.         0.02465651]
 [0.         0.         0.0273139 ]
 [0.14858439 0.         0.03119779]
 [0.14882482 0.         0.02547418]
 [0.14876471 0.14885862 0.02710948]
 [0.14612    0.14842357 0.02220356]
 [0.14587956 0.14795227 0.02465651]
 [0.144437   0.14635709 0.02220356]
 [0.14624021 0.14686465 0.02833597]
 [0.14822374 0.14762598 0.03140217]
 [0.15098866 0.14929366 0.03160658]
 [0.15074823 0.14980122 0.02751831]
 [0.15026737 0.15114261 0.02976685]
 [0.15068812 0.15197645 0.03303748]
 [0.15080833 0.15136013 0.02792713]
 [0.15128919 0.15132388 0.03140217]
 [0.14918545 0.15103385 0.025883  ]
 [0.14768278 0.14980122 0.02281681]
 [0.14563914 0.14827855 0.0244521 ]
 [0.14377583 0.14679215 0.0195462 ]
 [0.14239337 0.14443564 0.01811531]
 [0.14022954 0.14287673 0.01709325]
 [0.13980879 0.14204289 0.01811531]
 [0.13974868 0.14088278 0.0179109 ]
 [0.13842633 0.13965014 0.01259614]
 [0.13668323 0.13859878 0.01218731]
 [0.13578162 0.13819998 0.01484468]
 [0.13608215 0.13740239 0.01361819]
 [0.13698375 0.13693109 0.01525351]
 [0.13632257 0.13693109 0.01259614]
 [0.13638268 0.13722111 0.01382259]
 [0.13734438 0.13787368 0.0185241 ]
 [0.13884705 0.13859876 0.01770645]
 [0.13908747 0.13848999 0.01464022]
 [0.13872683 0.13932382 0.01729763]
 [0.13824597 0.13972261 0.01607113]
 [0.13776512 0.13874376 0.01300493]
 [0.13554116 0.13732986 0.00973434]
 [0.13415872 0.1367498  0.01136966]
 [0.13524066 0.13664105 0.01668442]]
(40, 3)
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm (LSTM)                  (None, 128)               67584
_________________________________________________________________
dense (Dense)                (None, 1)                 129
=================================================================
Total params: 67,713
Trainable params: 67,713
Non-trainable params: 0
_________________________________________________________________

In [30]:
from tensorflow.keras.callbacks import EarlyStopping

model.compile(loss='mse',optimizer='adam',metrics=['mse'])

early_stop = EarlyStopping(monitor='val_loss',patience=5)

model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=100,batch_size=16,callbacks=[early_stop])

Epoch 1/100
163/163 [==============================] - 3s 14ms/step - loss: 0.0018 - mse: 0.0018 - val_loss: 9.9214e-04 - val_mse: 9.9214e-04
Epoch 2/100
163/163 [==============================] - 2s 13ms/step - loss: 1.6352e-04 - mse: 1.6352e-04 - val_loss: 7.9743e-04 - val_mse: 7.9743e-04
Epoch 3/100
163/163 [==============================] - 2s 14ms/step - loss: 1.6740e-04 - mse: 1.6740e-04 - val_loss: 8.6625e-04 - val_mse: 8.6625e-04
Epoch 4/100
163/163 [==============================] - 2s 13ms/step - loss: 1.6180e-04 - mse: 1.6180e-04 - val_loss: 7.2728e-04 - val_mse: 7.2728e-04
Epoch 5/100
163/163 [==============================] - 2s 13ms/step - loss: 1.4341e-04 - mse: 1.4341e-04 - val_loss: 5.8661e-04 - val_mse: 5.8661e-04
Epoch 6/100
163/163 [==============================] - 2s 13ms/step - loss: 1.4302e-04 - mse: 1.4302e-04 - val_loss: 5.4156e-04 - val_mse: 5.4156e-04
Epoch 7/100
163/163 [==============================] - 2s 13ms/step - loss: 1.3431e-04 - mse: 1.3431e-04 - val_loss: 0.0011 - val_mse: 0.0011
Epoch 8/100
163/163 [==============================] - 2s 13ms/step - loss: 1.3235e-04 - mse: 1.3235e-04 - val_loss: 4.4448e-04 - val_mse: 4.4448e-04
Epoch 9/100
163/163 [==============================] - 2s 13ms/step - loss: 1.1279e-04 - mse: 1.1279e-04 - val_loss: 4.4730e-04 - val_mse: 4.4730e-04
Epoch 10/100
163/163 [==============================] - 2s 13ms/step - loss: 1.0910e-04 - mse: 1.0910e-04 - val_loss: 3.7909e-04 - val_mse: 3.7909e-04
Epoch 11/100
163/163 [==============================] - 2s 13ms/step - loss: 1.0037e-04 - mse: 1.0037e-04 - val_loss: 3.6036e-04 - val_mse: 3.6036e-04
Epoch 12/100
163/163 [==============================] - 2s 13ms/step - loss: 9.9983e-05 - mse: 9.9983e-05 - val_loss: 5.6097e-04 - val_mse: 5.6097e-04
Epoch 13/100
163/163 [==============================] - 2s 13ms/step - loss: 8.7850e-05 - mse: 8.7850e-05 - val_loss: 5.9484e-04 - val_mse: 5.9484e-04
Epoch 14/100
163/163 [==============================] - 2s 13ms/step - loss: 8.6584e-05 - mse: 8.6584e-05 - val_loss: 6.2019e-04 - val_mse: 6.2019e-04
Epoch 15/100
163/163 [==============================] - 2s 13ms/step - loss: 9.2762e-05 - mse: 9.2762e-05 - val_loss: 4.0053e-04 - val_mse: 4.0053e-04
Epoch 16/100
163/163 [==============================] - 2s 12ms/step - loss: 8.5353e-05 - mse: 8.5353e-05 - val_loss: 4.8439e-04 - val_mse: 4.8439e-04

In [38]:
pred = model.predict(x_test)

plt.figure(figsize=(12,6))

plt.title('3MA + 5MA + Adj Close , window_size = 40')
plt.ylabel('adj close')
plt.xlabel('period')
plt.plot(y_test,label='actual')
plt.plot(pred,label='prediction')
plt.grid()
plt.legend(loc='best')
plt.show()

array([[0.5791205 ],
       [0.5865539 ],
       [0.59138036],
       [0.5855054 ],
       [0.5783041 ],
       [0.57289714],
       [0.5656483 ],
       [0.56371117],
       [0.56013614],
       [0.55903786],
       [0.5623884 ],
       [0.5657887 ],
       [0.57053345],
       [0.5748769 ],
       [0.581829  ],
       [0.5850377 ],
       [0.5894858 ],
       [0.5943555 ],
       [0.597236  ],
       [0.59344596],
       [0.58678454],
       [0.5845917 ],
       [0.58939797],
       [0.59453243],
       [0.5938752 ],
       [0.5924713 ],
       [0.5921273 ],
       [0.58911836],
       [0.5826282 ],
       [0.57327145],
       [0.5594774 ],
       [0.5548321 ],
       [0.5618155 ],
       [0.5682225 ],
       [0.5817544 ],
       [0.5897589 ],
       [0.5935558 ],
       [0.5934218 ],
       [0.5975421 ],
       [0.59888417],
       [0.61081296],
       [0.63640714],
       [0.65193695],
       [0.65340906],
       [0.6478985 ],
       [0.6425887 ],
       [0.6545868 ],
       [0.6673304 ],
       [0.6701885 ],
       [0.67646897],
       [0.6813186 ],
       [0.67589366],
       [0.6759194 ],
       [0.686173  ],
       [0.6964895 ],
       [0.712598  ],
       [0.73031837],
       [0.73387057],
       [0.7435412 ],
       [0.7434263 ],
       [0.7441167 ],
       [0.7459903 ],
       [0.7479819 ],
       [0.7494088 ],
       [0.7475603 ],
       [0.7443173 ],
       [0.7422975 ],
       [0.73797345],
       [0.744338  ],
       [0.7724168 ],
       [0.799251  ],
       [0.8227512 ],
       [0.8483103 ],
       [0.87268364],
       [0.8891919 ],
       [0.88410586],
       [0.87841886],
       [0.9092378 ],
       [0.9496321 ],
       [0.97317326],
       [0.9739701 ],
       [0.966038  ],
       [0.9480769 ],
       [0.9187775 ],
       [0.9139998 ],
       [0.92128307],
       [0.93736714],
       [0.94106287],
       [0.9555554 ],
       [0.9481135 ],
       [0.93197256],
       [0.907829  ],
       [0.88380045],
       [0.8781124 ],
       [0.8899625 ],
       [0.90408546],
       [0.9001352 ],
       [0.89820933],
       [0.8928995 ],
       [0.8875385 ],
       [0.87757635],
       [0.886803  ],
       [0.900847  ],
       [0.90058666],
       [0.8892369 ],
       [0.8820011 ],
       [0.87670475],
       [0.874044  ],
       [0.87374544],
       [0.8943043 ],
       [0.89417106],
       [0.8958191 ],
       [0.89706045],
       [0.88857216],
       [0.8792981 ],
       [0.8733209 ],
       [0.86831445],
       [0.86370367],
       [0.8683669 ],
       [0.8783732 ],
       [0.87966245],
       [0.88357645],
       [0.8822494 ],
       [0.8837245 ],
       [0.8785698 ],
       [0.87497383],
       [0.87191635],
       [0.8663022 ],
       [0.86410165],
       [0.8657983 ],
       [0.8688586 ],
       [0.87669593],
       [0.8771736 ],
       [0.8842951 ],
       [0.9001483 ],
       [0.914602  ],
       [0.9249398 ],
       [0.9256538 ],
       [0.9171213 ],
       [0.9028087 ],
       [0.89152056],
       [0.8920782 ],
       [0.89696777],
       [0.9026869 ],
       [0.9049218 ],
       [0.90143603],
       [0.9011734 ],
       [0.8937134 ],
       [0.8870385 ],
       [0.88577956],
       [0.89137393],
       [0.8930108 ],
       [0.8882491 ],
       [0.88108814],
       [0.8752194 ],
       [0.8738287 ],
       [0.88001126],
       [0.88389105],
       [0.88316154],
       [0.88864744],
       [0.8807972 ],
       [0.86621356],
       [0.84692323],
       [0.84560853],
       [0.84735996],
       [0.8509533 ],
       [0.8526047 ],
       [0.8564887 ],
       [0.85618037],
       [0.85579956],
       [0.8542744 ],
       [0.85189325],
       [0.853171  ],
       [0.8571812 ],
       [0.8608597 ],
       [0.8638312 ],
       [0.8767933 ],
       [0.8824329 ],
       [0.881828  ],
       [0.8786352 ],
       [0.87124705],
       [0.86575896],
       [0.8636092 ],
       [0.86122495],
       [0.86289096],
       [0.8704191 ],
       [0.870971  ],
       [0.86706156],
       [0.8594488 ],
       [0.85497266],
       [0.85405695],
       [0.8615888 ],
       [0.87046576],
       [0.87758416],
       [0.8749125 ],
       [0.8684799 ],
       [0.85970086],
       [0.85402596],
       [0.85456014],
       [0.86198395]], dtype=float32)